// Generated by ChatGPT

using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

public class VignetteEffect : MonoBehaviour
{
    [Header("Settings")]
    [SerializeField] private float speed = 5f; // 진행 속도
    [SerializeField] private float max = 1f; // 최대치
    [SerializeField] private float min = 0.8f; // 최소치

    private Volume volume; // 볼륨
    private Vignette vignette; // 비네트

    private void Start()
    {
        // 참조
        volume = GetComponent<Volume>();
        volume.profile.TryGet(out vignette);
    }

    private void Update()
    {
        DrowsyVignette(); // 졸음 효과 처리
    }

    // 졸음 효과 처리
    private void DrowsyVignette()
    {
        // Sin 파형을 이용해 -1 ~ 1 범위의 값을 생성
        // Time.time * speed 로 깜빡이는 속도를 조절
        float t = (Mathf.Sin(Time.time * speed) + 1f) * 0.5f;

        // t 값을 0 ~ 1 범위로 정규화한 뒤
        // min ~ max 범위의 vignette 강도로 보간
        // → 부드럽게 어두워졌다가 밝아지는(꿈뻑꿈뻑) 효과
        vignette.intensity.value = Mathf.Lerp(min, max, t);
    }
}
