//Generated by GEMINI
using UnityEngine;

public class WeaponRecoil : MonoBehaviour
{
    [Header("Recoil Transform")]
    public Transform recoilHolder; // 리코일 효과를 적용할 부모 오브젝트 (Sway 오브젝트의 부모 권장)

    [Header("Initial Position")]
    public Vector3 initialPosition = new Vector3(0f, 0f, 0.5f); // 리코일이 적용되지 않은 기본 위치 (로컬 좌표)

    [Header("Recoil Settings")]
    // 반동이 돌아오는 속도 (값이 클수록 빨리 원상복구 됨)
    public float positionalReturnSpeed = 18f;
    public float rotationalReturnSpeed = 30f;

    // 반동이 튀는 속도 (값이 클수록 빠릿하게 튐)
    public float positionalSnappiness = 6f;
    public float rotationalSnappiness = 6f;

    [Header("Recoil Force")]
    // 한 발 쏠 때 적용할 반동의 힘 (X, Y, Z)
    // Rotation X: 위로 솟구치는 힘 (가장 중요)
    // Position Z: 뒤로 밀리는 힘
    public Vector3 recoilRotation = new Vector3(10f, 5f, 7f);
    public Vector3 recoilKickBack = new Vector3(0.015f, 0f, -0.2f);

    // 내부 계산용 변수 (Private)
    private Vector3 currentRecoilRotation;
    private Vector3 targetRecoilRotation;
    private Vector3 currentRecoilPosition;
    private Vector3 targetRecoilPosition;

    private void Update()
    {
        HandleRecoil();
    }

    // Update() 문 안에서 매 프레임 호출해 주세요.
    private void HandleRecoil()
    {
        // 1. 목표치(Target)를 0(원점)으로 복구 (반동 회복)
        targetRecoilPosition = Vector3.Lerp(targetRecoilPosition, initialPosition, positionalReturnSpeed * Time.deltaTime);
        targetRecoilRotation = Vector3.Lerp(targetRecoilRotation, Vector3.zero, rotationalReturnSpeed * Time.deltaTime);

        // 2. 현재값(Current)을 목표치(Target)로 이동 (반동 발생)
        currentRecoilPosition = Vector3.Slerp(currentRecoilPosition, targetRecoilPosition, positionalSnappiness * Time.deltaTime);
        currentRecoilRotation = Vector3.Slerp(currentRecoilRotation, targetRecoilRotation, rotationalSnappiness * Time.deltaTime);

        // 3. 실제 트랜스폼에 적용
        // 주의: recoilHolder가 없다면 transform을 직접 쓰되, Sway와 충돌 주의
        if (recoilHolder != null)
        {
            recoilHolder.localPosition = currentRecoilPosition;
            recoilHolder.localRotation = Quaternion.Euler(currentRecoilRotation);
        }
    }

    // 실제 총을 쏘는 Fire() 메서드 내부에서 '총알 나갈 때' 호출해 주세요.
    public void ApplyRecoil()
    {
        // 랜덤성을 부여하여 기계적인 느낌 제거

        // 회전 반동 (팔이 들림)
        targetRecoilRotation += new Vector3(
            recoilRotation.x, // 위로 솟구침 (고정값 권장)
            Random.Range(-recoilRotation.y, recoilRotation.y), // 좌우 랜덤 흔들림
            Random.Range(-recoilRotation.z, recoilRotation.z)  // 화면 기울기(Roll) 랜덤
        );

        // 위치 반동 (어깨 쪽으로 밀림)
        targetRecoilPosition += new Vector3(
            Random.Range(-recoilKickBack.x, recoilKickBack.x), // 좌우 미세 떨림
            Random.Range(-recoilKickBack.y, recoilKickBack.y), // 상하 미세 떨림
            recoilKickBack.z // 뒤로 후퇴 (음수 값이어야 함)
        );
    }
}
