// Generated by Gemini

Shader "Hidden/CustomFogRenderFeature"
{
    Properties
    {
        _MainTex ("Texture", 2D) = "white" {}
        _FogColor ("Fog Color", Color) = (0.5, 0.6, 0.7, 1)
        _FogDensity ("Fog Density", Range(0, 1)) = 0.05
        _FogOffset ("Fog Start Offset", Float) = 0
    }
    SubShader
    {
        Tags { "RenderType"="Opaque" "RenderPipeline" = "UniversalPipeline" }
        LOD 100
        ZWrite Off ZTest Always

        Pass
        {
            Name "CustomFogPass"

            HLSLPROGRAM
            #pragma vertex Vert
            #pragma fragment Frag

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DeclareDepthTexture.hlsl"
            #include "Packages/com.unity.render-pipelines.core/Runtime/Utilities/Blit.hlsl"

            struct FogAttributes
            {
                uint vertexID : SV_VertexID;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            struct FogVaryings
            {
                float4 positionCS : SV_POSITION;
                float2 texcoord   : TEXCOORD0;
                UNITY_VERTEX_OUTPUT_STEREO
            };

            float4 _FogColor;
            float _FogDensity;
            float _FogOffset;

            float4 _FlashLightPos;       // 빛의 월드 좌표
            float4 _FlashLightColor;     // 빛의 색상
            float _FlashLightRange;      // 빛의 범위
            float _FlashLightIntensity;  // 빛의 강도

            FogVaryings Vert(FogAttributes input)
            {
                FogVaryings output;
                UNITY_SETUP_INSTANCE_ID(input);
                UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(output);

                float4 pos = GetFullScreenTriangleVertexPosition(input.vertexID);
                float2 uv  = GetFullScreenTriangleTexCoord(input.vertexID);

                output.positionCS = pos;
                output.texcoord   = uv;
                return output;
            }

            half4 Frag(FogVaryings input) : SV_Target
            {
                UNITY_SETUP_STEREO_EYE_INDEX_POST_VERTEX(input);
                
                float4 color = SAMPLE_TEXTURE2D(_BlitTexture, sampler_LinearClamp, input.texcoord);
                float depth = SampleSceneDepth(input.texcoord);
                float linearDepth = LinearEyeDepth(depth, _ZBufferParams);

                // [추가된 코드 1] 현재 픽셀의 밝기(Brightness)를 계산합니다.
                // MuzzleFlash는 HDR 컬러를 사용하므로 1.0보다 훨씬 밝은 값을 가집니다.
                float maxBrightness = max(color.r, max(color.g, color.b));

                // 밝기가 1.0 ~ 3.0 이상이면 '발광체'로 인식하여 마스크를 생성 (0~1 범위)
                // 밝을수록 1에 가까워짐
                float emissionMask = smoothstep(0.8, 3.0, maxBrightness);

                // 1. 월드 포지션 재구성
                float3 worldPos = ComputeWorldSpacePosition(input.texcoord, depth, UNITY_MATRIX_I_VP);

                // 2. 안개 기본 계산
                float fogDistance = max(0, linearDepth - _FogOffset);
                float fogFactor = exp2(-_FogDensity * fogDistance); 

                // [추가된 코드 2] 발광체일 경우 안개 효과 제거 (FogFactor를 1로 강제)
                // emissionMask가 1이면(아주 밝으면) fogFactor도 1이 되어 안개가 사라짐
                fogFactor = saturate(fogFactor + emissionMask);

                // 3. 라이트 산란(Scattering) 효과 계산
                float distToLight = distance(worldPos, _FlashLightPos.xyz);
                
                float lightAtten = saturate(1.0 - (distToLight / _FlashLightRange));
                lightAtten = pow(lightAtten, 2.0); 

                // 밝은 물체 위에는 산란광도 굳이 그릴 필요가 없으므로 약화시킴 (선택 사항)
                float3 scattering = _FlashLightColor.rgb * _FlashLightIntensity * lightAtten * (1.0 - fogFactor) * (1.0 - emissionMask);

                // 4. 최종 색상 합성
                float3 finalFogColor = _FogColor.rgb + scattering;

                return half4(lerp(finalFogColor, color.rgb, saturate(fogFactor)), color.a);
            }
            ENDHLSL
        }
    }
}