// Generated by GEMINI

using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

// URP에서 커스텀 포그(Fog) 효과를 적용하기 위한 Renderer Feature
public class CustomFogFeature : ScriptableRendererFeature
{
    // 인스펙터에 노출될 설정 클래스
    [System.Serializable]
    public class Settings
    {
        // 포그 효과를 적용할 머티리얼
        public Material fogMaterial = null;

        // 렌더링 파이프라인 중 어느 시점에 이 패스를 실행할지 결정
        // 기본값은 포스트 프로세싱 직전
        public RenderPassEvent renderPassEvent = RenderPassEvent.BeforeRenderingPostProcessing;
    }

    // 인스펙터에서 조정 가능한 설정 인스턴스
    public Settings settings = new Settings();

    // 실제 렌더링을 담당하는 커스텀 패스
    CustomFogPass m_ScriptablePass;

    // 실제 포그 렌더링 로직을 수행하는 RenderPass
    class CustomFogPass : ScriptableRenderPass
    {
        // 포그 효과에 사용할 머티리얼
        public Material fogMaterial;

        // 카메라 컬러 버퍼 참조
        private RTHandle source;

        // 패스 실행 전에 필요한 입력 텍스처를 설정
        public override void Configure(CommandBuffer cmd, RenderTextureDescriptor cameraTextureDescriptor)
        {
            // 컬러 버퍼 + 깊이 버퍼를 입력으로 사용하겠다고 명시
            ConfigureInput(
                ScriptableRenderPassInput.Color |
                ScriptableRenderPassInput.Depth
            );
        }

        // 실제 렌더링이 수행되는 함수
        public override void Execute(ScriptableRenderContext context, ref RenderingData renderingData)
        {
            // 포그 머티리얼이 없으면 아무 작업도 하지 않음
            if (fogMaterial == null) return;

            // 카메라 컬러 타겟이 유효하지 않으면 실행 중지
            if (renderingData.cameraData.renderer.cameraColorTargetHandle == null) return;

            // 커맨드 버퍼 생성 (풀에서 가져옴)
            CommandBuffer cmd = CommandBufferPool.Get("Custom Fog Pass");

            // 현재 카메라의 컬러 타겟 핸들 가져오기
            source = renderingData.cameraData.renderer.cameraColorTargetHandle;

            // RTHandle과 실제 RenderTexture가 유효할 때만 Blit 수행
            if (source != null && source.rt != null)
            {
                // 현재 화면(source)에 포그 머티리얼을 사용해 덮어쓰기
                // 동일한 source → source로 Blit하여 포스트 프로세스처럼 동작
                Blitter.BlitCameraTexture(
                    cmd,
                    source,
                    source,
                    fogMaterial,
                    0 // 머티리얼의 첫 번째 패스 사용
                );
            }

            // 커맨드 버퍼 실행
            context.ExecuteCommandBuffer(cmd);

            // 커맨드 버퍼 반환 (메모리 누수 방지)
            CommandBufferPool.Release(cmd);
        }
    }

    // Renderer Feature가 생성될 때 한 번 호출됨
    public override void Create()
    {
        // 커스텀 패스 인스턴스 생성
        m_ScriptablePass = new CustomFogPass();

        // 인스펙터에서 설정한 렌더 패스 이벤트 적용
        m_ScriptablePass.renderPassEvent = settings.renderPassEvent;
    }

    // 매 프레임 렌더러에 패스를 추가하는 단계
    public override void AddRenderPasses(ScriptableRenderer renderer, ref RenderingData renderingData)
    {
        // 포그 머티리얼이 없으면 패스를 추가하지 않음
        // (에러 로그 없이 조용히 패스)
        if (settings.fogMaterial == null)
        {
            return;
        }

        // 인스펙터에서 변경된 머티리얼을 매 프레임 패스에 반영
        m_ScriptablePass.fogMaterial = settings.fogMaterial;

        // 렌더러에 커스텀 포그 패스 등록
        renderer.EnqueuePass(m_ScriptablePass);
    }
}
