// Generated by GEMINI

using UnityEngine;

// 에디터 모드에서도 실행되도록 설정
// (씬 뷰에서 조명 변화가 바로 포그에 반영됨)
[ExecuteInEditMode]
public class FlashToFog : MonoBehaviour
{
    // 이 스크립트가 붙은 오브젝트의 Light 컴포넌트
    private Light myLight;

    // 셰이더 전역 변수 ID 캐싱 (문자열 접근 비용 절감)
    private static readonly int FlashPosID = Shader.PropertyToID("_FlashLightPos");
    private static readonly int FlashColorID = Shader.PropertyToID("_FlashLightColor");
    private static readonly int FlashRangeID = Shader.PropertyToID("_FlashLightRange");
    private static readonly int FlashIntensityID = Shader.PropertyToID("_FlashLightIntensity");

    void Start()
    {
        // 같은 오브젝트에 붙어 있는 Light 컴포넌트 참조
        myLight = GetComponent<Light>();
    }

    void Update()
    {
        // Light가 없으면 아무 처리도 하지 않음 (안전 장치)
        if (myLight == null) return;

        // 라이트가 활성화되어 있고, 게임 오브젝트도 활성 상태일 때만 처리
        if (myLight.enabled && myLight.gameObject.activeInHierarchy)
        {
            // 손전등(또는 플래시)의 월드 위치를 전역 셰이더 변수로 전달
            Shader.SetGlobalVector(FlashPosID, transform.position);

            // 라이트 색상을 셰이더에 전달 (포그 색감에 반영)
            Shader.SetGlobalColor(FlashColorID, myLight.color);

            // 라이트의 유효 범위를 셰이더에 전달
            Shader.SetGlobalFloat(FlashRangeID, myLight.range);

            // 라이트 밝기를 안개 산란 강도로 변환
            // 0.05f는 포그 효과가 과도해지지 않도록 한 스케일 계수
            float fogScatteringIntensity = myLight.intensity * 0.05f;
            Shader.SetGlobalFloat(FlashIntensityID, fogScatteringIntensity);
        }
        else
        {
            // 라이트가 꺼졌거나 비활성화되었을 경우
            // 포그에 전달되는 플래시 영향력을 즉시 제거
            Shader.SetGlobalFloat(FlashIntensityID, 0f);
        }
    }

    void OnDisable()
    {
        // 오브젝트가 비활성화될 때도
        // 셰이더 전역 값이 남지 않도록 강제로 0으로 초기화
        Shader.SetGlobalFloat(FlashIntensityID, 0f);
    }
}
